---
title: "p8105 HW1 yh3555"
author: "Yuchen Hua"
date: "2022-09-21"
output: github_document
---

```{r}
library(tidyverse)
library(ggplot2)
```

## Problem 1

#### Load the penguins dataset
```{r}
data("penguins", package = "palmerpenguins")
```

#### Describe the data
```{r}
skimr::skim(penguins)
```

#### Make scatterplot
```{r}
flipper_vs_bill <- ggplot(penguins)+geom_point(mapping = aes(x=bill_length_mm, y=flipper_length_mm, color=species))
flipper_vs_bill
ggsave("penguine plot.pdf", flipper_vs_bill)
```
## Problem 2
```{r}
library(dplyr)
```
## Create Data Frame
```{r}
vec_numeric = rnorm(10)
vec_logical = vec_numeric > 0
vec_char = c('A', 'D', 'A', 'R', 'M', 'L', 'Q', 'P', 'C', 'C')
Vec_factor = factor(c('Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Transgender', 'Transgender', 'Transgender', 'Transgender'))
df = tibble(
  vec_numeric,
  vec_logical,
  vec_char,
  Vec_factor)
df
```

## Mean of variable
```{r}
mean(vec_numeric)
mean(vec_logical)
mean(vec_char)
mean(Vec_factor)
```